### pandas

> pandas is a powerfull python library for manipulation  and alanaysis of data 

> Its a open source library

> fast (built on top of numpy), flexible (different resource),productive library

In [105]:
pip  install pandas

Requirement already satisfied: pandas in c:\users\klemp\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (3.0.3)
Requirement already satisfied: numpy>=1.26.0 in c:\users\klemp\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from pandas) (2.4.6)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\klemp\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata in c:\users\klemp\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from pandas) (2026.2)
Requirement already satisfied: six>=1.5 in c:\users\klemp\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 24.0 -> 26.1.2
[notice] To update, run: C:\Users\klemp\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\python.exe -m pip install --upgrade pip

In [106]:
import pandas as pd

In [107]:
pd.__version__

'3.0.3'

### series - one dimensional array (data structure) with lable

In [108]:
l1=[1,2,3,4,5]
type(l1)

list

In [109]:
pd.Series(l1)

0    1
1    2
2    3
3    4
4    5
dtype: int64

In [110]:
s=pd.Series(l1,index =["a","b","c","d","e"],name ="My Series")

In [111]:
s

a    1
b    2
c    3
d    4
e    5
Name: My Series, dtype: int64

In [112]:
type(s)

pandas.Series

In [113]:
s.index

Index(['a', 'b', 'c', 'd', 'e'], dtype='str')

In [114]:
s.values

array([1, 2, 3, 4, 5])

> Note :index in Series are immutable(cant change)

In [115]:
s.index[0] ='z'

TypeError: Index does not support mutable operations

In [ ]:
# Changing the index of a pandas series

s.rename(index={'b':'y'},inplace=True)

In [ ]:
s

a    1
y    2
c    3
d    4
e    5
Name: My Series, dtype: int64

### DataFrame - Its a 2d array (just like tables )

rows and cols

In [ ]:
Dict = {'Name':['virat','Rohit','Dhoni','jadeja','rajat','virat'],
'Age':[34,33,36,40,38,40],
'Marks':[85,70,75,65,90,35],
'Role':['Batsman','Batsman','Wicket Keeper','All Rounder','Batsman','Bolwer']}
df= pd.DataFrame(Dict)

In [ ]:
df

     Name  Age  Marks           Role
0   virat   34     85        Batsman
1   Rohit   33     70        Batsman
2   Dhoni   36     75  Wicket Keeper
3  jadeja   40     65    All Rounder
4   rajat   38     90        Batsman
5   virat   40     35         Bolwer

In [ ]:
type(df)

pandas.DataFrame

In [ ]:
df.tail(2)

    Name  Age  Marks     Role
4  rajat   38     90  Batsman
5  shami   40     35   Bolwer

In [ ]:
len(df)

6

In [ ]:
df.count()

Name     6
Age      6
Marks    6
Role     6
dtype: int64

In [ ]:
df.columns

Index(['Name', 'Age', 'Marks', 'Role'], dtype='str')

In [ ]:
df['Name']

0     virat
1     Rohit
2     Dhoni
3    jadeja
4     rajat
5     shami
Name: Name, dtype: str

In [ ]:
df['Name'].value_counts()

Name
virat     2
Rohit     1
Dhoni     1
jadeja    1
rajat     1
Name: count, dtype: int64

#### Basic operation

> Importing data set from different files

> Importing tabular dataset

In [ ]:
stock_df=pd.read_csv(r"C:\Users\klemp\OneDrive\Desktop\Data analyist\Data sets\ETH_1h.csv")

In [ ]:
stock_df

                   Date  Symbol    Open    High     Low   Close      Volume
0      2020-03-13 08-PM  ETHUSD  129.94  131.82  126.87  128.71  1940673.93
1      2020-03-13 07-PM  ETHUSD  119.51  132.02  117.10  129.94  7579741.09
2      2020-03-13 06-PM  ETHUSD  124.47  124.85  115.50  119.51  4898735.81
3      2020-03-13 05-PM  ETHUSD  124.08  127.42  121.63  124.47  2753450.92
4      2020-03-13 04-PM  ETHUSD  124.85  129.51  120.17  124.08  4461424.71
...                 ...     ...     ...     ...     ...     ...         ...
23669  2017-07-01 03-PM  ETHUSD  265.74  272.74  265.00  272.57  1500282.55
23670  2017-07-01 02-PM  ETHUSD  268.79  269.90  265.00  265.74  1702536.85
23671  2017-07-01 01-PM  ETHUSD  274.83  274.93  265.00  268.79  3010787.99
23672  2017-07-01 12-PM  ETHUSD  275.01  275.01  271.00  274.83   824362.87
23673  2017-07-01 11-AM  ETHUSD  279.98  279.99  272.10  275.01   679358.87

[23674 rows x 7 columns]

top 5 rows

In [ ]:
stock_df.head()

               Date  Symbol    Open    High     Low   Close      Volume
0  2020-03-13 08-PM  ETHUSD  129.94  131.82  126.87  128.71  1940673.93
1  2020-03-13 07-PM  ETHUSD  119.51  132.02  117.10  129.94  7579741.09
2  2020-03-13 06-PM  ETHUSD  124.47  124.85  115.50  119.51  4898735.81
3  2020-03-13 05-PM  ETHUSD  124.08  127.42  121.63  124.47  2753450.92
4  2020-03-13 04-PM  ETHUSD  124.85  129.51  120.17  124.08  4461424.71

Top 10 rows

In [ ]:
stock_df.head(10)

               Date  Symbol    Open    High     Low   Close      Volume
0  2020-03-13 08-PM  ETHUSD  129.94  131.82  126.87  128.71  1940673.93
1  2020-03-13 07-PM  ETHUSD  119.51  132.02  117.10  129.94  7579741.09
2  2020-03-13 06-PM  ETHUSD  124.47  124.85  115.50  119.51  4898735.81
3  2020-03-13 05-PM  ETHUSD  124.08  127.42  121.63  124.47  2753450.92
4  2020-03-13 04-PM  ETHUSD  124.85  129.51  120.17  124.08  4461424.71
5  2020-03-13 03-PM  ETHUSD  128.39  128.90  116.06  124.85  7378976.00
6  2020-03-13 02-PM  ETHUSD  134.03  137.90  125.50  128.39  3733916.89
7  2020-03-13 01-PM  ETHUSD  131.35  140.95  128.99  134.03  9582732.93
8  2020-03-13 12-PM  ETHUSD  128.93  134.60  126.95  131.35  3906590.52
9  2020-03-13 11-AM  ETHUSD  132.60  133.17  126.01  128.93  3311080.29

> bottom 5 rows

In [ ]:
stock_df.tail()

                   Date  Symbol    Open    High    Low   Close      Volume
23669  2017-07-01 03-PM  ETHUSD  265.74  272.74  265.0  272.57  1500282.55
23670  2017-07-01 02-PM  ETHUSD  268.79  269.90  265.0  265.74  1702536.85
23671  2017-07-01 01-PM  ETHUSD  274.83  274.93  265.0  268.79  3010787.99
23672  2017-07-01 12-PM  ETHUSD  275.01  275.01  271.0  274.83   824362.87
23673  2017-07-01 11-AM  ETHUSD  279.98  279.99  272.1  275.01   679358.87

In [ ]:
## Number of rows in dataframe
len(stock_df)

23674

> Access column names of dataframe

In [ ]:
stock_df.columns

Index(['Date', 'Symbol', 'Open', 'High', 'Low', 'Close', 'Volume'], dtype='str')

In [ ]:
## accessing a column in a dataframe

stock_df['Open']

0        129.94
1        119.51
2        124.47
3        124.08
4        124.85
          ...
23669    265.74
23670    268.79
23671    274.83
23672    275.01
23673    279.98
Name: Open, Length: 23674, dtype: float64

In [ ]:
stock_df['Close']

0        128.71
1        129.94
2        119.51
3        124.47
4        124.08
          ...
23669    272.57
23670    265.74
23671    268.79
23672    274.83
23673    275.01
Name: Close, Length: 23674, dtype: float64

In [ ]:
## accessing a column in a dataframe

stock_df[['Open','Close','Volume']]

         Open   Close      Volume
0      129.94  128.71  1940673.93
1      119.51  129.94  7579741.09
2      124.47  119.51  4898735.81
3      124.08  124.47  2753450.92
4      124.85  124.08  4461424.71
...       ...     ...         ...
23669  265.74  272.57  1500282.55
23670  268.79  265.74  1702536.85
23671  274.83  268.79  3010787.99
23672  275.01  274.83   824362.87
23673  279.98  275.01   679358.87

[23674 rows x 3 columns]

In [ ]:
 stock_df.index

RangeIndex(start=0, stop=23674, step=1)

In [ ]:
stock_df.columns

Index(['Date', 'Symbol', 'Open', 'High', 'Low', 'Close', 'Volume'], dtype='str')

## Accessing rows

loc - lable location

In [ ]:
stock_df.loc[23672]

Date      2017-07-01 12-PM
Symbol              ETHUSD
Open                275.01
High                275.01
Low                  271.0
Close               274.83
Volume           824362.87
Name: 23672, dtype: object

In [ ]:
stock_df.loc[[23672],['Date','Open']]

                   Date    Open
23672  2017-07-01 12-PM  275.01

In [ ]:
stock_df.loc[[23672],['Date','Close']]

                   Date   Close
23672  2017-07-01 12-PM  274.83

In [ ]:
stock_df['Open']

0        129.94
1        119.51
2        124.47
3        124.08
4        124.85
          ...
23669    265.74
23670    268.79
23671    274.83
23672    275.01
23673    279.98
Name: Open, Length: 23674, dtype: float64

In [ ]:
stock_df.loc[23672,['Date','Close','Open']]

Date     2017-07-01 12-PM
Close              274.83
Open               275.01
Name: 23672, dtype: object

#### slicing in loc (labeled location)

df.loc['row_lable_1','row_lable_3','column_lable_1','column_lable-2']

In [ ]:
stock_df.loc[23672,'Open': 'Close']

Open     275.01
High     275.01
Low       271.0
Close    274.83
Name: 23672, dtype: object

## iloc - index based location ,when we dont know lables for rows and column

In [ ]:
stock_df

                   Date  Symbol    Open    High     Low   Close      Volume
0      2020-03-13 08-PM  ETHUSD  129.94  131.82  126.87  128.71  1940673.93
1      2020-03-13 07-PM  ETHUSD  119.51  132.02  117.10  129.94  7579741.09
2      2020-03-13 06-PM  ETHUSD  124.47  124.85  115.50  119.51  4898735.81
3      2020-03-13 05-PM  ETHUSD  124.08  127.42  121.63  124.47  2753450.92
4      2020-03-13 04-PM  ETHUSD  124.85  129.51  120.17  124.08  4461424.71
...                 ...     ...     ...     ...     ...     ...         ...
23669  2017-07-01 03-PM  ETHUSD  265.74  272.74  265.00  272.57  1500282.55
23670  2017-07-01 02-PM  ETHUSD  268.79  269.90  265.00  265.74  1702536.85
23671  2017-07-01 01-PM  ETHUSD  274.83  274.93  265.00  268.79  3010787.99
23672  2017-07-01 12-PM  ETHUSD  275.01  275.01  271.00  274.83   824362.87
23673  2017-07-01 11-AM  ETHUSD  279.98  279.99  272.10  275.01   679358.87

[23674 rows x 7 columns]

In [ ]:
stock_df.iloc[2,0:7]

Date      2020-03-13 06-PM
Symbol              ETHUSD
Open                124.47
High                124.85
Low                  115.5
Close               119.51
Volume          4898735.81
Name: 2, dtype: object

In [ ]:
stock_df.iloc[2,2] # row index and column index

np.float64(124.47)

In [ ]:
stock_df.iloc[3,[2,4]] #multiple column index

Open    124.08
Low     121.63
Name: 3, dtype: float64

In [ ]:
 stock_df.iloc[1:6,2:6]

     Open    High     Low   Close
1  119.51  132.02  117.10  129.94
2  124.47  124.85  115.50  119.51
3  124.08  127.42  121.63  124.47
4  124.85  129.51  120.17  124.08
5  128.39  128.90  116.06  124.85

In [ ]:
f1 = stock_df['High'] > 130

stock_df[f1]

stock_gt_130 = stock_df[f1]

In [ ]:
stock_gt_130.reset_index(drop=True,inplace=True)

In [ ]:
stock_gt_130

                   Date  Symbol    Open    High     Low   Close      Volume
0      2020-03-13 08-PM  ETHUSD  129.94  131.82  126.87  128.71  1940673.93
1      2020-03-13 07-PM  ETHUSD  119.51  132.02  117.10  129.94  7579741.09
2      2020-03-13 02-PM  ETHUSD  134.03  137.90  125.50  128.39  3733916.89
3      2020-03-13 01-PM  ETHUSD  131.35  140.95  128.99  134.03  9582732.93
4      2020-03-13 12-PM  ETHUSD  128.93  134.60  126.95  131.35  3906590.52
...                 ...     ...     ...     ...     ...     ...         ...
21608  2017-07-01 03-PM  ETHUSD  265.74  272.74  265.00  272.57  1500282.55
21609  2017-07-01 02-PM  ETHUSD  268.79  269.90  265.00  265.74  1702536.85
21610  2017-07-01 01-PM  ETHUSD  274.83  274.93  265.00  268.79  3010787.99
21611  2017-07-01 12-PM  ETHUSD  275.01  275.01  271.00  274.83   824362.87
21612  2017-07-01 11-AM  ETHUSD  279.98  279.99  272.10  275.01   679358.87

[21613 rows x 7 columns]

Adding new column

In [ ]:
stock_df.index

RangeIndex(start=0, stop=23674, step=1)

In [ ]:
len(stock_df)

23674

In [ ]:
stock_df['Random_col'] = list(range(1,len(stock_df)+1))

In [ ]:
stock_df

,Date,Symbol,Open,High,Low,Close,Volume,Random_col
0,2020-03-13 08-PM,ETHUSD,129.94,131.82,126.87,128.71,1940673.93,1
1,2020-03-13 07-PM,ETHUSD,119.51,132.02,117.10,129.94,7579741.09,2
2,2020-03-13 06-PM,ETHUSD,124.47,124.85,115.50,119.51,4898735.81,3
3,2020-03-13 05-PM,ETHUSD,124.08,127.42,121.63,124.47,2753450.92,4
4,2020-03-13 04-PM,ETHUSD,124.85,129.51,120.17,124.08,4461424.71,5
...,...,...,...,...,...,...,...,...
23669,2017-07-01 03-PM,ETHUSD,265.74,272.74,265.00,272.57,1500282.55,23670
23670,2017-07-01 02-PM,ETHUSD,268.79,269.90,265.00,265.74,1702536.85,23671
23671,2017-07-01 01-PM,ETHUSD,274.83,274.93,265.00,268.79,3010787.99,23672
23672,2017-07-01 12-PM,ETHUSD,275.01,275.01,271.00,274.83,824362.87,23673
23673,2017-07-01 11-AM,ETHUSD,279.98,279.99,272.10,275.01,679358.87,23674

Dropping column

In [ ]:
stock_df.drop(columns=['Random_col'],inplace=True)

In [ ]:
stock_df

                   Date  Symbol    Open    High     Low   Close      Volume
0      2020-03-13 08-PM  ETHUSD  129.94  131.82  126.87  128.71  1940673.93
1      2020-03-13 07-PM  ETHUSD  119.51  132.02  117.10  129.94  7579741.09
2      2020-03-13 06-PM  ETHUSD  124.47  124.85  115.50  119.51  4898735.81
3      2020-03-13 05-PM  ETHUSD  124.08  127.42  121.63  124.47  2753450.92
4      2020-03-13 04-PM  ETHUSD  124.85  129.51  120.17  124.08  4461424.71
...                 ...     ...     ...     ...     ...     ...         ...
23669  2017-07-01 03-PM  ETHUSD  265.74  272.74  265.00  272.57  1500282.55
23670  2017-07-01 02-PM  ETHUSD  268.79  269.90  265.00  265.74  1702536.85
23671  2017-07-01 01-PM  ETHUSD  274.83  274.93  265.00  268.79  3010787.99
23672  2017-07-01 12-PM  ETHUSD  275.01  275.01  271.00  274.83   824362.87
23673  2017-07-01 11-AM  ETHUSD  279.98  279.99  272.10  275.01   679358.87

[23674 rows x 7 columns]

In [127]:
stock_df.drop(columns=['Close'],inplace=True)